apiVersion: v1
kind: Pod
metadata:
  name: cudatestpodchaos
  namespace: gpu
  labels:
    app: cuda
spec:
  containers:
    - name: cudatestpodchaos
      image: nvidia/cuda:13.1.1-cudnn-runtime-ubuntu24.04
      command: ["sleep", "3600"]
      resources:
        limits:
          nvidia.com/gpu: 48

