apiVersion: apps/v1
kind: Deployment
metadata:
  name: a30
spec:
  replicas: 1000
  selector:
    matchLabels:
      gpu: a30
  template:
    metadata:
      labels:
        gpu: a30
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - kwok
      tolerations:
        - key: "kwok.x-k8s.io/node"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: a30
          image: nvidia/cuda:13.1.1-cudnn-runtime-ubuntu24.04
          command: ["sleep", "3600"]
          resources:
            limits:
              nvidia.com/gpu: 1
              cpu: "10m"
              memory: "32Mi"
            requests:
              nvidia.com/gpu: 1
              cpu: "10m"
              memory: "32Mi"
