apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    kwok.x-k8s.io/node: fake
  labels:
    kubernetes.io/arch: arm64
    kubernetes.io/hostname: falconshores-node-0
    kubernetes.io/os: linux
    type: kwok
    gpu: falconshores
    run.ai/simulated-gpu-node-pool: falconshores
  name: falconshores-node-0
spec:
status:
  capacity:
    cpu: "32"
    memory: "128Gi"
    pods: "10000"
    intel.com/gpu: "10"
  allocatable:
    cpu: "32"
    memory: "128Gi"
    pods: "10000"
    intel.com/gpu: "10"
